# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Practice
email: 
description: >
  "Nothing endures but change." &mdash Heraclitus 
  > So keep learning, practicing, and sharing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tuyendq
github_username:  tuyendq

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman